In [1]:
a = 6

In [2]:
a = 8 

In [3]:
import numpy as np

In [4]:
it = [3, 6, 7, 11]

In [6]:
n = np.array(it)

In [7]:
type(n)

numpy.ndarray

In [28]:
twod = np.array([[1, 2] , [3, 4]])
twod

array([[1, 2],
       [3, 4]])

In [11]:
y = np.array([1, 2, 3, "77"])

y

array(['1', '2', '3', '77'], dtype='<U11')

In [12]:
n.shape

(4,)

In [15]:
twod.shape

(2, 2)

In [16]:
n.size

4

In [29]:
twod.size

4

In [30]:
list(range(10,11))

[10]

In [31]:
list(range(10,21))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [32]:
list(range(10,21,3))

[10, 13, 16, 19]

In [33]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
np.arange(10,21,5)

array([10, 15, 20])

In [35]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1]

In [36]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [41]:
arr = np.arange(50).reshape(5,10) 

In [42]:
arr1 = np.arange(50)

In [43]:
arr2 = arr1.reshape(5,10)

In [44]:
arr1[0] = 100

In [45]:
arr1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49])

In [46]:
arr2

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])